### ISSUE TITLE
Terminal not resetting.

### ISSUE THREAD

**Issue by bakpakin** [pepe/jff#1]
Works well when I actually select something, but when I press escape or ctrl-c out of the selection, my terminal is left in a strange state. Likely a problem with the underlying termbox lib, but I found the issue here.

**Comment by pepe** [comment]
Oh. Thanks! 

I will look at it. I am not cleaning up anything it seems.

**Comment by pepe** [comment]
It did the same thing to me, but as I am using it only in one shot alacrity windows I have never registered it. The problem was, that on esc/ctrl-c I immediately called `os/exit` and it wreaks havoc with the term.  

It is fixed in 0a24c8f. Thank you for the catch.

**Comment by pepe** [comment]
On the theme of the termbox lib, I would love to wrap https://nick-black.com/dankwiki/index.php/Notcurses one day, if I ever learn to code in C.

**Comment by pepe** [comment]
I have refactored the whole thing a little and fixed this issue in place, without the condition in main. 

Thank you again.
