### ISSUE TITLE
Black boxes?

### ISSUE THREAD

**Issue by sogaiu** [pepe/jff#2]
On an Ubuntu-derivative system, the following leads to some "black boxes":
```
cd /usr
less $(rg FLT_MIN | jff)
```
![black-box-in-jff](https://user-images.githubusercontent.com/33044872/85831577-69fe5e00-b786-11ea-966a-d9bdf6ad453f.png)

My installation is of commit: a0024d8d1a099c60909e93644804b884ce21d4eb

**Comment by pepe** [comment]
Thanks for the headup. I will investigate. Please can you provide inane -a and terminal app name?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sogaiu** [comment]
It happens with both xterm and xfce4-terminal.

`uname -a` slightly edited is:
```
Linux <something> 5.3.0-61-generic #55-Ubuntu SMP Fri Jun 19 11:16:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pepe** [comment]
Thanks. I am looking at it on the bigger screen, isn't it just the tabulators? Because it does not seem to be missing any text.

Anyway, I will look at it on my computer later. I am usually only listing shorter items, so thanks for the use-case.

**Comment by sogaiu** [comment]
Below is a screenshot with xterm.  There are 2 black boxes that I see -- they are near the top (below and on either side of the word "xterm" in the title bar).  I see that the green "highlight" is broken by the two black boxes (as is the line below).

Are they more apparent now?  Or may be I'm missing something :)

![black-boxes-in-jff-xterm](https://user-images.githubusercontent.com/33044872/85851755-32ec7480-b7a7-11ea-8067-8d815dcf973a.png)

**Comment by sogaiu** [comment]
Oh, may be the green highlighting is supposed to get broken up!

Ha ha ha.  Sorry, it's as you say.  Just my imagination!

**Comment by pepe** [comment]
Lovely, but missing green bg is annoying still.

And fear not, this issue brought to the attention that `jff` was printing on non-visible cells (beyond right border of the window). And one pretty cool idea: pass a string with Janet function to transform the result.

So, for example, you can filter filename from `rg` output with: 

```
rg janet_panic | jff "> " "" '|(first (string/split ":" $))'
```

Tell me how cool is that! :rofl: 

I know it could be done easily with another pipe, but it will be much more work (need to read stdin, print it back)

**Comment by sogaiu** [comment]
It sounds like it would provide additional practical opportunities for folks to practice / hone their Janet skillz ;)
